application:
  title: na-app
  version: v1.0



spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/na_app

security:
  jwt:
    secret-key: 841113a1-9083-43ab-ab88-972070c907b5
    expiration: 3600000
    refresh-expiration: 86400000

springdoc:
  api-docs:
    enabled: true